### ISSUE TITLE
kire parchis na toh?

### ISSUE THREAD

**Issue by tripulse** [telugu-boy/librecord#2]

**Comment by tripulse** [comment]
here geli?

**Comment by tripulse** [comment]
ay beriye ay

**Comment by tripulse** [comment]
arrey noob coder achis

**Comment by telugu-boy** [comment]
https://user-images.githubusercontent.com/42505125/139571043-2c27b59c-4bd2-412f-9204-02704f787f29.mp4

**Comment by telugu-boy** [comment]
0ight kigga'-3

**Comment by tripulse** [comment]
kire? khub toh boro boro batla marchili
dekhli je tor bapero bap thake
kire? baper na ta sunbi naki?
sune ne
sound center!
mojaaaaam!
*ei he hahahaha ei ha ha eh hi hi hi hiiiii*
